### PR TITLE
Add autocompletion

### PR DESCRIPTION
**Pull request by kernicPanel**
Hi 
As I'm coming from cheat, I borrowed them this : https://github.com/chrisallenlane/cheat/wiki/Enabling-Command-line-Autocompletion

I don't know if the added test is well done, but they're all passing with python 3.6.

After copying autocompletion/tldr.bash to /etc/bash_completion.d/ (on ubuntu), autocompletion will be available like this : 
```bash
~/tldr.py$ tldr find ta[tab]
tabula  tac     tail    tar     task
```

### CODE REVIEW

**Comment by lord63** [comment]
Hey, it looks great! 👍  I'll look into this feature this weekend, will ping you back if I have some ideas :)

**Comment by kernicPanel** [comment]
Hi
I've reworked on this PR from this http://click.pocoo.org/5/bashcomplete/
Now all commands levels are completed: 
```bash
~/tldr.py$ tldr [tab]
find     init     list     locate   reindex  update

~/tldr.py$ tldr find ta[tab]
tabula  tac     tail    tar     task
```
Only find and locate commands gets completed with page names.

**Comment by lord63** [comment]
@kernicPanel Hi, sorry for the late response. Changed my job recently, new place, new work, new life, pretty busy these day. I'll try to get some time to review this pr these days.

**Comment by kernicPanel** [comment]
Hi, @lord63 
No problem, there's no rush wish this.
I wish you're enjoying your new life :slightly_smiling_face: 

Just a question, do you prefer PR into master or dev ?

**Comment by lord63** [comment]
Ah, seems I missed the PR again. I've changed the base to dev and I'll merge it.

We'll add zsh autocompletion in the future. Thanks you again. 🎆 🎆 🎆

**Pull request merged**
